/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current AI-processing consent (NFR5d) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Consent"];
                    };
                };
            };
        };
        put?: never;
        /** Record consent with timestamp and policy version (X8) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConsentCreate"];
                };
            };
            responses: {
                /** @description Recorded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Consent"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects the caller is a member of (FR3c) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a project; the creator becomes Owner (FR3a) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                /** @description Name already used by this owner */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Invalid name */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                /** @description Not found or no access (NFR4) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/inputs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit pasted requirement text (FR1a) and start extraction */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InputCreate"];
                };
            };
            responses: {
                /** @description Extraction queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                /** @description No AI consent recorded (X8) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/statements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** Requirement statements R-001… (FR4g) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RequirementStatement"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** Extracted items, paginated (FR5a) */
        get: {
            parameters: {
                query?: {
                    category?: components["schemas"]["ItemCategory"];
                    page?: number;
                    page_size?: number;
                };
                header?: never;
                path: {
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ItemPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                item_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit an item; origin becomes user-edited (FR5b) and confirmation is cleared (FR5e) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: components["parameters"]["ProjectId"];
                    item_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ItemUpdate"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExtractedItem"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/projects/{project_id}/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm the current extraction (FR5e) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Confirmed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/generations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a generation run with a locked diagram-type selection (FR9d) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GenerationCreate"];
                };
            };
            responses: {
                /** @description Queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                /** @description Extraction not confirmed (FR5e) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/diagrams": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiagramSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        /** Job status, polled by the progress indicator (FR10g) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    job_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagrams/{diagram_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                diagram_id: components["parameters"]["DiagramId"];
            };
            cookie?: never;
        };
        /** One diagram version. The picture itself is the PNG from /export. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    diagram_id: components["parameters"]["DiagramId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Diagram"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagrams/{diagram_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                diagram_id: components["parameters"]["DiagramId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edit a diagram in plain language ("rename Browse canteen menu to Browse menu card"). Returns the new version; the old one is kept. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    diagram_id: components["parameters"]["DiagramId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RevisionCreate"];
                };
            };
            responses: {
                /** @description New version */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Diagram"];
                    };
                };
                /** @description The instruction could not be applied */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagrams/{diagram_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                diagram_id: components["parameters"]["DiagramId"];
            };
            cookie?: never;
        };
        /** The rendered diagram as a still PNG, shown in the viewer and downloaded by Export (FR18a — 2x, capped at 8000 px) */
        get: {
            parameters: {
                query: {
                    format: "png";
                };
                header?: never;
                path: {
                    diagram_id: components["parameters"]["DiagramId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Plain-language message safe to show the user */
            detail: string;
            code?: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        Consent: {
            /** @description True only if consent matches the current AI section of the policy */
            consented: boolean;
            policy_version?: string | null;
            /** Format: date-time */
            consented_at?: string | null;
            current_policy_version: string;
        };
        ConsentCreate: {
            policy_version: string;
        };
        /** @enum {string} */
        Role: "owner" | "editor" | "viewer";
        Project: {
            id: string;
            name: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            statement_count: number;
            item_count: number;
            /** @description Latest extraction job */
            extraction: components["schemas"]["Job"] | null;
            /** @description Current extraction is confirmed (cleared by any change) */
            confirmed: boolean;
            /** Format: date-time */
            confirmed_at?: string | null;
            diagram_count: number;
        };
        ProjectCreate: {
            name: string;
        };
        InputCreate: {
            text: string;
        };
        SourceLocation: {
            document: string;
            page?: number | null;
            paragraph?: number | null;
        };
        RequirementStatement: {
            id: string;
            /** @description Project-unique */
            ref: string;
            text: string;
            /** @description Label the input already carried */
            label?: string | null;
            source: components["schemas"]["SourceLocation"];
        };
        /** @enum {string} */
        ItemCategory: "actor" | "entity" | "process" | "data_flow" | "data_store" | "interaction" | "relationship";
        /** @enum {string} */
        ItemOrigin: "system-extracted" | "user-added" | "user-edited";
        /** @enum {string} */
        ItemQualifier: "minimal" | "low-confidence" | "incomplete" | "order-uncertain" | "needs-review";
        ExtractedItem: {
            id: string;
            category: components["schemas"]["ItemCategory"];
            name: string;
            description?: string | null;
            origin: components["schemas"]["ItemOrigin"];
            qualifiers: components["schemas"]["ItemQualifier"][];
            /** @description Source requirement statement IDs */
            statement_ids: string[];
            /** @description For flows */
            source_item_id?: string | null;
            target_item_id?: string | null;
            /** @description e.g. association */
            relation_type?: string | null;
        };
        ItemPage: {
            items: components["schemas"]["ExtractedItem"][];
            total: number;
            page: number;
            page_size: number;
            /** @description Item count per category */
            counts: {
                [key: string]: number;
            };
        };
        ItemUpdate: {
            name?: string;
            description?: string | null;
        };
        /** @enum {string} */
        DiagramType: "use_case" | "class" | "activity" | "sequence" | "dfd" | "component";
        GenerationCreate: {
            diagram_types: components["schemas"]["DiagramType"][];
        };
        /** @enum {string} */
        JobStatus: "queued" | "running" | "succeeded" | "failed";
        Job: {
            id: string;
            /** @enum {string} */
            kind: "extraction" | "generation";
            status: components["schemas"]["JobStatus"];
            queue_position?: number | null;
            progress: {
                step: number;
                total: number;
                /** @description e.g. "Generating diagram 1 of 1" */
                label: string;
            };
            diagram_types?: components["schemas"]["DiagramType"][];
            diagram_ids?: string[];
            error?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
        };
        DiagramSummary: {
            id: string;
            type: components["schemas"]["DiagramType"];
            title: string;
            /** Format: date-time */
            created_at: string;
            /** @description The version this one was edited from; null for a fresh generation */
            parent_id: string | null;
            /** @description The edit request that produced this version; null for a fresh generation */
            instruction: string | null;
        };
        Diagram: components["schemas"]["DiagramSummary"];
        RevisionCreate: {
            instruction: string;
        };
    };
    responses: never;
    parameters: {
        ProjectId: string;
        DiagramId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
